name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature or improvement.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Why is this useful?
      placeholder: What problem does it solve or what does it improve?
    validations:
      required: false
